### PR TITLE
fix date parsing inconsistencies, closes #4

### LINKED ISSUE #4: util.date ignores timezones
The following tests fail when run on a machine not in the `America/New_York` timezone:

- `should return a valid date from string`
- `should return a valid date from number with timezone`

### PR DESCRIPTION
**Pull request by kg6zvp**

### CODE REVIEW

File: test/date.js [hunk 1]
```diff
@@ -17,7 +17,13 @@ describe('date', () => {
     should.not.exist(util.date('abc', 'America/New_York'))
   })
   it('should return a valid date from string', async () => {
```
Comment (contra) [inline test/date.js]: Can you add tests that:
- ensure dates with an existing timezone are either converted, or not modified
- test ISO string inputs

Should also probably include changes in docs since this behavior is a little complex to describe

File: src/util/date.js [hunk 2]
```diff
@@ -12,12 +12,18 @@ const produceDateFormat = (timestamp) => {
...
+  const dv = new Date(v) // js Date does a good job of parsing/coercing weird strings to a date, do this now and hang onto it for later
   if (isNaN(dv)) return
-  const epoch = parseNum(v)
-  if (epoch) {
+  const epoch = parseNum(v) // try to parse the input number or string to a number which will be interpreted as epoch time
+  if (epoch) { // if it's epoch time, we can use unix in moment
     return produceDateFormat(moment.unix(epoch / 1000).utc())
   }
+  if (/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(([+-]\d\d:\d\d)|Z)?$/i.test(v)) { //check if it matches ISO 8601 with a regex; necessary because moment will sometimes parse things that aren't true ISO 8601 even when set to strict
+    const mt = moment(v, moment.ISO_8601, true) //true to use strict parsing in moment
```
Comment (contra) [inline src/util/date.js]: do we need to use moment to parse it again if it already matched the regex?
